#cloud-config
---
write_files:
  - path: /home/core/setup_calico.sh
    permissions: 777
    owner: root
    content: |
      #!/usr/bin/bash -e
      # Add /opt/bin to the _front_ of the PATH.
      # Can't directly write to .profile since it's a symlink to a RO filesystem      
      rm /home/core/.bashrc
      echo 'PATH=/opt/bin:$PATH' > /home/core/.bashrc
      echo "Defaults  secure_path=/opt/bin:$PATH" >>/etc/sudoers.d/path
      mkdir -p /opt/bin
      mkdir -p /opt/bin
      wget -N -O /opt/bin/calicoctl http://www.projectcalico.org/builds/calicoctl?circleci-branch=v0.16.1-candidate
      chmod +x /opt/bin/calicoctl
      mkdir -p /etc/rkt/net.d
      chmod a+w /etc/rkt/net.d
      wget -N -P /etc/rkt/net.d https://github.com/projectcalico/calico-cni/releases/download/v1.0.0/calico
      chmod +x /etc/rkt/net.d/calico
      rkt --insecure-options=image fetch docker://nginx
      rkt --insecure-options=image fetch docker://busybox
      rkt --insecure-options=image fetch docker://calico/node

coreos:
  update:
    reboot-strategy: off
  etcd2:
    name: "etcdserver"
    listen-client-urls: http://0.0.0.0:2379
    advertise-client-urls: http://$private_ipv4:2379
    initial-cluster: etcdserver=http://$private_ipv4:2380
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://0.0.0.0:2380    
  units:
    - name: "etcd2.service"
      command: "start"
    - name: calico-download.service
      runtime: true
      command: start
      content: |
        [Unit]
        Description=Download calico
        After=network-online.target
        Requires=network-online.target
        
        [Service]
        User=root
        ExecStart=/home/core/setup_calico.sh
        RemainAfterExit=yes
        Type=oneshot

        [Install]
        WantedBy=multi-user.target

